import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'PCBs',
        {
          type: 'autogenerated',
          dirName: 'PCBs', // Generate sidebar slice from docs/tutorials/easy
        },
        'How-To',
        {
          type: 'autogenerated',
          dirName: 'tutorial-doc-how-to', // Generate sidebar slice from docs/tutorials/advanced
        },
      ],
    },
  ],
  fundamentalsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'fundamentals',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  // fundamentalSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
