import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  electricalDocumentationSidebar: [
    'rover-document',
    {
      type: 'category',
      label: 'Electrical Documentation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'electricalDocumentation',
        },
      ],
    },
  ],

  electricalHandbookSidebar: [
    {
      type: 'autogenerated',
      dirName: 'electricalHandbook',
    },
  ],

  harnessingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'harnessing',
    },
  ],

};

export default sidebars;